apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poacpm-deploy
  labels:
    app: poacpm
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: poacpm
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          ports:
            - containerPort: 80
        - name: poacpm
          image: 308453953340.dkr.ecr.ap-northeast-1.amazonaws.com/poacpm/poacpm
          ports:
            - containerPort: 4000
          env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_default_region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-secrets
                  key: slack_webhook_url
            - name: AWS_ES_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: aws-es-endpoint
                  key: aws_es_endpoint
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      imagePullSecrets:
        - name: ecr

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.8
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=poac.pm
        - --provider=aws
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id=extdns
